In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
weights = pd.read_csv("original_data/weights1.csv")
weights2 = pd.read_csv("original_data/weights2.csv")
weights = pd.concat([weights, weights2], ignore_index=True)
weights

,OCCURNUM,qstnum,repwgt0,repwgt1,repwgt2,repwgt3,repwgt4,repwgt5,repwgt6,repwgt7,...,repwgt151,repwgt152,repwgt153,repwgt154,repwgt155,repwgt156,repwgt157,repwgt158,repwgt159,repwgt160
0,1,14,18354163,10438492,10407387,28068302,25562833,9239434,25338398,25701567,...,10895492,31037674,9263588,24989376,8651019,23992521,27458755,22802523,26921460,9028737
1,2,14,15592437,8650848,7739514,23599044,22150186,7661903,20928499,24058785,...,9142763,27457903,8064288,19715055,7889177,20023445,24539323,20821892,22804294,7763269
2,1,15,16356249,8971846,7819705,24359971,21130796,8033700,24966868,21950496,...,8970494,22956112,9292178,25490285,7864233,23294925,19066812,23322929,23187256,8032997
3,1,16,20773863,12256987,10094193,28950309,26670581,8927895,30159278,31383567,...,12579129,30210036,11522337,27180683,9795101,25067470,27903109,29132044,28331760,10088447
4,2,16,16796510,9358118,8017431,25625108,24611988,8170753,24141884,24525276,...,9598023,22642743,10367559,21832240,9384531,22057325,25366842,23213102,23656517,8461291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99058,1,69460,3872403,3811524,3867477,1184134,6392906,3869526,3833685,4185059,...,3946475,3955011,4098830,1141866,7098608,1220946,4046508,6799129,5947367,7015049
99059,1,69461,3872403,3811524,3867477,1184134,6392906,3869526,3833685,4185059,...,3946475,3955011,4098830,1141866,7098608,1220946,4046508,6799129,5947367,7015049
99060,2,69461,3332493,3369042,3339441,1046782,5289272,3467648,3184734,3487858,...,3398154,3455348,3389339,972960,5565823,1068255,3141941,5549270,5110794,5729614
99061,1,69464,2790829,2731309,837142,830413,4724120,5051157,2624563,5274098,...,4617975,2631165,807997,2960079,812894,4881043,2910442,964690,834369,2604438
99062,2,69464,2405480,2407276,725336,677759,4006436,4092427,2524321,4474437,...,4174586,2259161,651293,2601965,648107,3932865,2863624,797046,702423,2373449

In [25]:
data = pd.read_csv('original_data/nov24pub_first_half.csv')
data2 = pd.read_csv('original_data/nov24pub_second_half.csv')
data = pd.concat([data, data2], ignore_index=True)
data

,HRHHID,HRMONTH,HRYEAR4,HURESPLI,HUFINAL,FILLER,HETENURE,HEHOUSUT,HETELHHD,HETELAVL,...,PRSUPINT,PES1,PES2,PES3,PES4,PES5,PES6,PES7,PRS8,PESCK4
0,84055620110148,11,2024,-1,219,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,521800504640811,11,2024,1,219,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,510421864001780,11,2024,-1,219,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,7180159540041,11,2024,-1,219,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,71062004118993,11,2024,-1,219,NaN,1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126681,658604017243570,11,2024,-1,218,NaN,2,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
126682,140784500685805,11,2024,-1,218,NaN,1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
126683,181202500665725,11,2024,1,218,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
126684,940325328011460,11,2024,1,218,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
126685,790456071508119,11,2024,-1,218,NaN,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [26]:
def filter_rows_by_negative_one_pct(df, threshold=0.2, missing_value=-1, inplace=False):
    # threshold: fraction of cols with missing_value to mark row as bad
    # e.g. 0.5 means ">= 50% of columns are -1"
    bad = (df == missing_value).sum(axis=1) / df.shape[1] >= threshold
    n_bad = int(bad.sum())
    n_total = len(df)
    print(f"{n_bad} rows out of {n_total} have >= {threshold*100:.1f}% of columns == {missing_value}")
    if inplace:
        df.drop(index=df[bad].index, inplace=True)
        print(f"dropped {n_bad} rows, remaining {len(df)} rows")
        return df
    df_clean = df.loc[~bad].reset_index(drop=True)
    print(f"returning cleaned df with {len(df_clean)} rows")
    return df_clean

### USED TO CREATE PRE AND POST DROP COMPARISON PLOTS --- IGNORE ---

# df_clean = filter_rows_by_negative_one_pct(data)

# thresholds = np.linspace(0.0, 1.0, 101)
# remaining_counts = []

# for t in thresholds:
#     df_tmp = filter_rows_by_negative_one_pct(data, threshold=t)
#     remaining_counts.append(len(df_tmp))

# print("data original shape:", data.shape)
# print("rows remaining at thresholds (0..100%):", remaining_counts[:5], "...", remaining_counts[-5:])

# plt.figure(figsize=(8, 5))
# plt.plot(thresholds * 100, remaining_counts, marker="o", markersize=3)
# plt.xlabel("threshold % of columns == -1")
# plt.ylabel("rows remaining")
# plt.title("Rows remaining after filtering at each -1 threshold PreDrop")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(8, 5))
# plt.hist(remaining_counts, bins=20, edgecolor="k")
# plt.xlabel("rows remaining")
# plt.ylabel("frequency")
# plt.title("Histogram of remaining row counts over thresholds")
# plt.show()

In [27]:
data['HRINTSTA'].value_counts()

# 1 = Interview

# 2 = Type A Noninterview (These records represent households that were eligible
# for the November CPS interview but were not interviewed because no one was
# home, household members were temporarily absent, etc.)

# 3 = Type B Noninterview (These records represent sample addresses determined to
# be ineligible for the CPS by virtue of a temporary situation, such as being
# vacant, nonresidential, etc. These households could become eligible for a CPS
# interview.)

# 4 = Type C Noninterview (These recordsrepresentsample addresses determined to be
# ineligible for CPS by virtue of a permanent change such as demolished,
# condemned, etc. These addresses will not be visited again for CPS interviews.)

# We should only keep rows where HRINTSTA == 1, as these are the only rows that represent actual interviews. The other rows represent non-interviews or ineligible addresses, which are not useful for our analysis.
data = data[data['HRINTSTA'] == 1].reset_index(drop=True)

In [28]:
(data.where(data == -1).count() / len(data) * 100).sort_values(ascending=True).head(90)
# We can also get rid of columns that have a certain percentage of NA values, as these are also likely to be uninformative. 
# We can also get rid of columns that have a certain percentage of 0 values, as these are also likely to be uninformative. 


### Values that have 0% of -1 values (i.e. no missing data)

# HRHHID    HOUSEHOLD IDENTIFIER
# GTCBSA    SPECIFIC METROPOLITAN CBSA CODE  (SEE GEOGRAPHIC ATTACHMENT)
# GTCO      FIPS COUNTY CODE
# GTCBSAST  PRINCIPAL CITY/BALANCE STATUS 
# GTMETSTA  METROPOLITAN STATUS
# GTINDVPC  INDIVIDUAL PRINCIPAL CITY
# GTCBSASZ  Metropolitan Area (CBSA) SIZE (Population)
# GTCSA     Consolidated Statistical Area (CSA) FIPS CODE (SEE GEOGRAPHIC ATTACHMEN
# PTWK      WEEKLY EARNINGS – TOP CODE ****
# PRTFAGE   TOP CODE FLAG FOR AGE **** 
# PWCMPWGT  Composited Final Weight. Used to create BLS's published labor force statistics (4 implied decimal places)
# PTOT      WEEKLY OVERTIME AMOUNT – TOP CODE ****
# GEDIV     DIVISION
# OCCURNUM  Unique person identifier. Valid only within any specific month. 
# HXPHONEO  ALLOCATION FLAG 
# HXTELAVL  ALLOCATION FLAG  
# HXTELHHD  ALLOCATION FLAG
# HXFAMINC  ALLOCATION FLAG
# HXHOUSUT  ALLOCATION FLAG
# HXTENURE  ALLOCATION FLAG
# PWFMWGT   FAMILY WEIGHT (4 IMPLIED DECIMALS) ONLY USED FOR TALLYING FAMILY CHARACTERISTICS.
# PWLGWGT   LONGITUDINAL WEIGHT (4 IMPLIED DECIMALS) ONLY FOUND ON ADULT RECORDS MATCHED FROM MONTH TO MONTH. (USED FOR GROSS FLOWS ANALYSIS)
# PWORWGT   OUTGOING ROTATION WEIGHT (4 IMPLIED DECIMALS) USED FOR TALLYING INFORMATION COLLECTED ONLY IN 
# PWSSWGT   FINAL WEIGHT (4 IMPLIED DECIMAL PLACES) USED FOR MOST TABULATIONS, CONTROLLED TO INDEPENDENT ESTIMATES FOR 1) STATES; 2) ORIGIN, SEX, AND AGE; AND 3) AGE, RA 
# PWVETWGT  VETERANS WEIGHT (4 IMPLIED DECIMALS) USED FOR TALLYING VETERAN'S DATA ONLY, CONTROLLED TO ESTIMATES OF VETERANS SUPPLIED BY
# QSTNUM    Unique household identifier. Valid only within any specific month. 
# GEREG     REGION
# GESTFIPS  STATE CODE
# HUFINAL   FINAL OUTCOME CODE 
# PTHR      HOURLY PAY – TOP CODE ****
# HWHHWGT   HOUSEHOLD WEIGHT (4 IMPLIED DECIMAL PLACES) USED FOR TALLYING HOUSEHOLD CHARACTERISTICS  
# HEPHONEO  IS A TELEPHONE INTERVIEW ACCEPTABLE?
# HRNUMHOU  TOTAL NUMBER OF PERSONS LIVING IN THE HOUSEHOLD (HOUSEHOLD ME
# HRHTYPE   HOUSEHOLD TYPE
# HRMIS     MONTH-IN-SAMPLE 
# HRLONGLK  LONGITUDINAL LINK INDICATOR EDITED UNIVERSE: ALL HHLDs IN SAMPLE 
# HRHHID2   HOUSEHOLD IDENTIFIER (part 2)
# HRYEAR4   YEAR OF INTERVIEW
# HEHOUSUT  TYPE OF HOUSING UNIT
# HRMONTH   MONTH OF INTERVIEW 
# HUPRSCNT  NUMBER OF ACTUAL AND ATTEMPTED PERSONAL CONTACTS

HRHHID       0.000000
QSTNUM       0.000000
OCCURNUM     0.000000
PXDIPGED     0.000000
PXHGCOMP     0.000000
              ...
HUBUS        0.018170
HUINTTYP     6.536245
PEAFNOW     16.557140
PRIOELG     16.557140
PXCOHAB     16.557140
Length: 90, dtype: float64

In [29]:
for df_name in ['data', 'data2']:
    if df_name in globals():
        df = globals()[df_name]
        keep = ~(df == -1).all(axis=1)
        globals()[df_name] = df.loc[keep].reset_index(drop=True)
        print(f"{df_name}: removed {len(df) - keep.sum()} rows, remaining {keep.sum()}")

data: removed 0 rows, remaining 99063
data2: removed 0 rows, remaining 63343

In [30]:
df_clean = filter_rows_by_negative_one_pct(data)

thresholds = np.linspace(0.0, 1.0, 101)
remaining_counts = []

for t in thresholds:
    df_tmp = filter_rows_by_negative_one_pct(data, threshold=t)
    remaining_counts.append(len(df_tmp))

print("data original shape:", data.shape)
print("rows remaining at thresholds (0..100%):", remaining_counts[:5], "...", remaining_counts[-5:])

plt.figure(figsize=(8, 5))
plt.plot(thresholds * 100, remaining_counts, marker="o", markersize=3)
plt.xlabel("threshold % of columns == -1")
plt.ylabel("rows remaining")
plt.title("Rows remaining after filtering at each -1 threshold PostDrop")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.hist(remaining_counts, bins=20, edgecolor="k")
plt.xlabel("rows remaining")
plt.ylabel("frequency")
plt.title("Histogram of remaining row counts over thresholds")
plt.show()

99063 rows out of 99063 have >= 20.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 0.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 1.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 2.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 3.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 4.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 5.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 6.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 7.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 8.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 9.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 10.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 11.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 12.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 13.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 14.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 15.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 16.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 17.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 18.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 19.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 20.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 21.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 22.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 23.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 24.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 25.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 26.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 27.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 28.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 29.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 30.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 31.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 32.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 33.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 34.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 35.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 36.0% of columns == -1
returning cleaned df with 0 rows
99063 rows out of 99063 have >= 37.0% of columns == -1
returning cleaned df with 0 rows
99060 rows out of 99063 have >= 38.0% of columns == -1
returning cleaned df with 3 rows
99040 rows out of 99063 have >= 39.0% of columns == -1
returning cleaned df with 23 rows
98971 rows out of 99063 have >= 40.0% of columns == -1
returning cleaned df with 92 rows
98813 rows out of 99063 have >= 41.0% of columns == -1
returning cleaned df with 250 rows
98650 rows out of 99063 have >= 42.0% of columns == -1
returning cleaned df with 413 rows
98534 rows out of 99063 have >= 43.0% of columns == -1
returning cleaned df with 529 rows
98220 rows out of 99063 have >= 44.0% of columns == -1
returning cleaned df with 843 rows
97115 rows out of 99063 have >= 45.0% of columns == -1
returning cleaned df with 1948 rows
94035 rows out of 99063 have >= 46.0% of columns == -1
returning cleaned df with 5028 rows
91198 rows out of 99063 have >= 47.0% of columns == -1
returning cleaned df with 7865 rows
89330 rows out of 99063 have >= 48.0% of columns == -1
returning cleaned df with 9733 rows
88241 rows out of 99063 have >= 49.0% of columns == -1
returning cleaned df with 10822 rows
85838 rows out of 99063 have >= 50.0% of columns == -1
returning cleaned df with 13225 rows
75652 rows out of 99063 have >= 51.0% of columns == -1
returning cleaned df with 23411 rows
65373 rows out of 99063 have >= 52.0% of columns == -1
returning cleaned df with 33690 rows
56954 rows out of 99063 have >= 53.0% of columns == -1
returning cleaned df with 42109 rows
53051 rows out of 99063 have >= 54.0% of columns == -1
returning cleaned df with 46012 rows
51667 rows out of 99063 have >= 55.0% of columns == -1
returning cleaned df with 47396 rows
50732 rows out of 99063 have >= 56.0% of columns == -1
returning cleaned df with 48331 rows
50023 rows out of 99063 have >= 57.0% of columns == -1
returning cleaned df with 49040 rows
48629 rows out of 99063 have >= 58.0% of columns == -1
returning cleaned df with 50434 rows
46428 rows out of 99063 have >= 59.0% of columns == -1
returning cleaned df with 52635 rows
42975 rows out of 99063 have >= 60.0% of columns == -1
returning cleaned df with 56088 rows
39588 rows out of 99063 have >= 61.0% of columns == -1
returning cleaned df with 59475 rows
32766 rows out of 99063 have >= 62.0% of columns == -1
returning cleaned df with 66297 rows
20196 rows out of 99063 have >= 63.0% of columns == -1
returning cleaned df with 78867 rows
17356 rows out of 99063 have >= 64.0% of columns == -1
returning cleaned df with 81707 rows
16753 rows out of 99063 have >= 65.0% of columns == -1
returning cleaned df with 82310 rows
16735 rows out of 99063 have >= 66.0% of columns == -1
returning cleaned df with 82328 rows
16735 rows out of 99063 have >= 67.0% of columns == -1
returning cleaned df with 82328 rows
16735 rows out of 99063 have >= 68.0% of columns == -1
returning cleaned df with 82328 rows
16735 rows out of 99063 have >= 69.0% of columns == -1
returning cleaned df with 82328 rows
16735 rows out of 99063 have >= 70.0% of columns == -1

KeyboardInterrupt:

In [ ]:
data['PESEX'].value_counts(dropna=False)

2    50665
1    48398
Name: PESEX, dtype: int64

Looking into PWSSWGT as the main weight column

In [ ]:
under18 = data[data['PRTAGE'] < 18]
#len(under18)
under18['PWSSWGT'] = under18['PWSSWGT'] / 10000
child_votes = under18[under18['PES1'] == 1]['PWSSWGT'].sum()
print(under18['PES1'].value_counts())
print(child_votes)

-1    20081
Name: PES1, dtype: int64
0.0

C:\Users\chris\AppData\Local\Temp\ipykernel_26628\2981289860.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  under18['PWSSWGT'] = under18['PWSSWGT'] / 10000

In [ ]:
# eliminate under 18  
data = data[data['PRTAGE'] >= 18]
# edit weight (PWSSWGT) to have correct decimal placement
data['PWSSWGT'] = data['PWSSWGT'] / 10000

In [ ]:
# count of voters? 
nvoters = data[data['PES1'] == 1]['PWSSWGT'].sum()
print(f"Estimated voters: {nvoters:,.0f}")
print("Total vote count in the 2024 Presidential election was about 155 million")

Estimated voters: 154,307,706
Total vote count in the 2024 Presidential election was about 155 million

In [ ]:
turnout_sex = (
    data.groupby(['PESEX', 'PES1'])['PWSSWGT']
    .sum()
    .unstack()
)
print(turnout_sex)
# PESEX: 1 = male, 2 = female
# PES1 (vote?): 1 = yes, 2 = no

PES1             -3            -2            -1             1             2
PESEX
1      1.659425e+06  2.170948e+06  2.510079e+07  7.277608e+07  2.501910e+07
2      1.870221e+06  1.805289e+06  2.496904e+07  8.153163e+07  2.346062e+07

In [ ]:
turnout_males = turnout_sex[1][1] / turnout_sex.loc[1].sum()
turnout_females = turnout_sex[1][2] / turnout_sex.loc[2].sum()
print(f"Male Turnout: {turnout_males}")
print(f"Female Turnout: {turnout_females}")
print("woohoo")

Male Turnout: 0.5742774148246865
Female Turnout: 0.6100986467359265
woohoo

In [ ]:
data['PRTAGE'].value_counts()

80    2672
85    2180
64    1371
61    1365
62    1362
      ...
74    1011
75     996
76     988
78     817
79     635
Name: PRTAGE, Length: 64, dtype: int64

Model attempt

In [ ]:
from sklearn.model_selection import train_test_split

#X = data
#y = data['voted']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1848)
train, test = train_test_split(
    data, test_size = 0.3, random_state = 1848, stratify = data['voted']
)

lg_model_0 = smf.logit(
    formula= 'voted ~ PESEX + PRTAGE + PTDTRACE + PEEDUCA', data = train
)
result = lg_model_0.fit(
    method = 'bfgs', var_weights = train['PWSSWGT'], disp=False
)
print(result.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                  voted   No. Observations:                55287
Model:                          Logit   Df Residuals:                    55282
Method:                           MLE   Df Model:                            4
Date:                Mon, 06 Apr 2026   Pseudo R-squ.:                 0.09523
Time:                        10:13:53   Log-Likelihood:                -33392.
converged:                       True   LL-Null:                       -36907.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -10.6596      0.162    -65.733      0.000     -10.977     -10.342
PESEX          0.0719      0.019      3.851      0.000       0.035       0.109
PRTAGE         0.0225      0.001     44.254      0.000       0.021       0.023
PTDTRACE      -0.1205      0.007    -16.742      0.000      -0.135      -0.106
PEEDUCA        0.2478      0.004     64.050      0.000       0.240       0.255
==============================================================================

c:\Users\chris\anaconda3\Lib\site-packages\statsmodels\base\optimizer.py:18: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method bfgs is: gtol, norm, epsilon. The list of unsupported keyword arguments passed include: var_weights. After release 0.14, this will raise.
  warnings.warn(

Removing useless allocation flags before fitting

In [ ]:
bad_cols = [col for col in data.columns if col.startswith(('PX', 'HX'))]
data_cleaner = data.drop(columns= bad_cols)
print(f"Remaining columns: {len(data_cleaner.columns)}")

Remaining columns: 300

In [ ]:
train, test = train_test_split(
    data, test_size = 0.3, random_state = 1848, stratify = data_cleaner['voted']
)

lg_model_0 = smf.logit(
    formula= 'voted ~ PESEX + PRTAGE + PTDTRACE + PEEDUCA', data = train
)
result = lg_model_0.fit(
    method = 'bfgs', var_weights = train['PWSSWGT'], disp=False
)
print(result.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                  voted   No. Observations:                55287
Model:                          Logit   Df Residuals:                    55282
Method:                           MLE   Df Model:                            4
Date:                Mon, 06 Apr 2026   Pseudo R-squ.:                 0.09523
Time:                        10:29:22   Log-Likelihood:                -33392.
converged:                       True   LL-Null:                       -36907.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -10.6596      0.162    -65.733      0.000     -10.977     -10.342
PESEX          0.0719      0.019      3.851      0.000       0.035       0.109
PRTAGE         0.0225      0.001     44.254      0.000       0.021       0.023
PTDTRACE      -0.1205      0.007    -16.742      0.000      -0.135      -0.106
PEEDUCA        0.2478      0.004     64.050      0.000       0.240       0.255
==============================================================================

c:\Users\chris\anaconda3\Lib\site-packages\statsmodels\base\optimizer.py:18: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method bfgs is: gtol, norm, epsilon. The list of unsupported keyword arguments passed include: var_weights. After release 0.14, this will raise.
  warnings.warn(