In [ ]:
# YOUR_API_KEY = "2e33e72535f647091cf522d7d465bf87"

In [5]:
!pip install fredapi

Collecting fredapi
  Downloading fredapi-0.5.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: pandas in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from fredapi) (2.3.1)
Requirement already satisfied: numpy>=1.22.4 in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from pandas->fredapi) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from pandas->fredapi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from pandas->fredapi) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from pandas->fredapi) (2026.1)
Requirement already satisfied: six>=1.5 in ./Users/ellawileman/anaconda3/envs/ds_env/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->fredapi) (1.17.0)
Downloading fredapi-0.5.2-py3-none-any.whl (11 kB)
Installing collected packages: fredapi
Successfully installed fredapi-0.5.2

In [3]:
import pandas as pd
import numpy as np
from fredapi import Fred

fred = Fred(api_key=YOUR_API_KEY)

states = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
    "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
    "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
    "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
    "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
]

In [4]:
def get_fred_series(series_id, state):
    s = fred.get_series(series_id)
    df = s.reset_index()
    df.columns = ["date", "value"]
    df["state"] = state
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    return df

In [5]:
unemp_list = []
for s in states:
    try:
        df = get_fred_series(f"{s}UR", s)
        unemp_list.append(df)
    except:
        pass

unemp = pd.concat(unemp_list)

In [15]:
unemp

          date  value state
0   1976-01-01    6.7    AL
1   1976-02-01    6.6    AL
2   1976-03-01    6.6    AL
3   1976-04-01    6.5    AL
4   1976-05-01    6.4    AL
..         ...    ...   ...
596 2025-09-01    3.4    WY
597 2025-10-01    NaN    WY
598 2025-11-01    3.5    WY
599 2025-12-01    3.5    WY
600 2026-01-01    3.6    WY

[30049 rows x 3 columns]

In [6]:
income_list = []
for s in states:
    try:
        df = get_fred_series(f"{s}PCPI", s)
        income_list.append(df)
    except:
        pass

income = pd.concat(income_list)

In [18]:
income

         date    value state
0  1929-01-01    319.0    AL
1  1930-01-01    263.0    AL
2  1931-01-01    220.0    AL
3  1932-01-01    159.0    AL
4  1933-01-01    164.0    AL
..        ...      ...   ...
91 2020-01-01  65094.0    WY
92 2021-01-01  70962.0    WY
93 2022-01-01  76394.0    WY
94 2023-01-01  81918.0    WY
95 2024-01-01  85945.0    WY

[4758 rows x 3 columns]

In [34]:
type(income["date"][1])

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_72813/3168435861.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(income["date"][1])

pandas._libs.tslibs.timestamps.Timestamp

In [33]:
income["date"] = pd.to_datetime(income["date"])
unemp["date"] = pd.to_datetime(unemp["date"])

In [38]:
income["year"] = income["date"].dt.year
unemp["year"] = unemp["date"].dt.year

unemp["month"] = unemp["date"].dt.month

In [45]:
income

                                    date    value state  year
1970-01-01 00:00:00.000000000 1929-01-01    319.0    AL  1929
1970-01-01 00:00:00.000000001 1930-01-01    263.0    AL  1930
1970-01-01 00:00:00.000000002 1931-01-01    220.0    AL  1931
1970-01-01 00:00:00.000000003 1932-01-01    159.0    AL  1932
1970-01-01 00:00:00.000000004 1933-01-01    164.0    AL  1933
...                                  ...      ...   ...   ...
1970-01-01 00:00:00.000000091 2020-01-01  65094.0    WY  2020
1970-01-01 00:00:00.000000092 2021-01-01  70962.0    WY  2021
1970-01-01 00:00:00.000000093 2022-01-01  76394.0    WY  2022
1970-01-01 00:00:00.000000094 2023-01-01  81918.0    WY  2023
1970-01-01 00:00:00.000000095 2024-01-01  85945.0    WY  2024

[4758 rows x 4 columns]

In [39]:
unemp

          date  value state  year  month
0   1976-01-01    6.7    AL  1976      1
1   1976-02-01    6.6    AL  1976      2
2   1976-03-01    6.6    AL  1976      3
3   1976-04-01    6.5    AL  1976      4
4   1976-05-01    6.4    AL  1976      5
..         ...    ...   ...   ...    ...
596 2025-09-01    3.4    WY  2025      9
597 2025-10-01    NaN    WY  2025     10
598 2025-11-01    3.5    WY  2025     11
599 2025-12-01    3.5    WY  2025     12
600 2026-01-01    3.6    WY  2026      1

[28246 rows x 5 columns]

In [142]:
income_filteryear = income[(income["year"] >= 2010) & (income["year"] <= 2024)]
income_filteryear

                                    date    value state  year
1970-01-01 00:00:00.000000081 2010-01-01  33848.0    AL  2010
1970-01-01 00:00:00.000000082 2011-01-01  34884.0    AL  2011
1970-01-01 00:00:00.000000083 2012-01-01  35559.0    AL  2012
1970-01-01 00:00:00.000000084 2013-01-01  35706.0    AL  2013
1970-01-01 00:00:00.000000085 2014-01-01  36722.0    AL  2014
...                                  ...      ...   ...   ...
1970-01-01 00:00:00.000000091 2020-01-01  65094.0    WY  2020
1970-01-01 00:00:00.000000092 2021-01-01  70962.0    WY  2021
1970-01-01 00:00:00.000000093 2022-01-01  76394.0    WY  2022
1970-01-01 00:00:00.000000094 2023-01-01  81918.0    WY  2023
1970-01-01 00:00:00.000000095 2024-01-01  85945.0    WY  2024

[750 rows x 4 columns]

In [143]:
unemp_filteryear = unemp[(unemp["year"] >= 2010) & (unemp["year"] <= 2024)]
unemp_filteryear

          date  value state  year  month
408 2010-01-01   11.0    AL  2010      1
409 2010-02-01   11.0    AL  2010      2
410 2010-03-01   10.9    AL  2010      3
411 2010-04-01   10.5    AL  2010      4
412 2010-05-01   10.3    AL  2010      5
..         ...    ...   ...   ...    ...
583 2024-08-01    3.2    WY  2024      8
584 2024-09-01    3.3    WY  2024      9
585 2024-10-01    3.3    WY  2024     10
586 2024-11-01    3.3    WY  2024     11
587 2024-12-01    3.3    WY  2024     12

[8460 rows x 5 columns]

In [144]:
unemp_octnov = unemp_filteryear[(unemp_filteryear["month"] == 10) | (unemp_filteryear["month"] == 11)]
unemp_octnov

          date  value state  year  month
417 2010-10-01   10.1    AL  2010     10
418 2010-11-01   10.1    AL  2010     11
429 2011-10-01    9.1    AL  2011     10
430 2011-11-01    8.9    AL  2011     11
441 2012-10-01    7.8    AL  2012     10
..         ...    ...   ...   ...    ...
562 2022-11-01    3.4    WY  2022     11
573 2023-10-01    2.8    WY  2023     10
574 2023-11-01    2.8    WY  2023     11
585 2024-10-01    3.3    WY  2024     10
586 2024-11-01    3.3    WY  2024     11

[1410 rows x 5 columns]

In [145]:
#rename months 
unemp_octnov.loc[unemp_octnov['month'] == 10, 'newmonth'] = 'october'
unemp_octnov.loc[unemp_octnov['month'] == 11, 'newmonth'] = 'november'

# remove date columns 
unemp_octnov = unemp_octnov.drop(columns=["date", "month"])
unemp_octnov = unemp_octnov.rename(columns={"newmonth":"month", "value":"unemployment_pct"})
income_filteryear = income_filteryear.reset_index()
income_filteryear["value"] = income_filteryear["value"].astype(int)
income_filteryear = income_filteryear[["value", "state", "year"]]

income_filteryear = income_filteryear.rename(columns={"value":"percapita_personalincome"})

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_72813/1065967751.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemp_octnov.loc[unemp_octnov['month'] == 10, 'newmonth'] = 'october'

In [146]:
income_filteryear

     percapita_personalincome state  year
0                       33848    AL  2010
1                       34884    AL  2011
2                       35559    AL  2012
3                       35706    AL  2013
4                       36722    AL  2014
..                        ...   ...   ...
745                     65094    WY  2020
746                     70962    WY  2021
747                     76394    WY  2022
748                     81918    WY  2023
749                     85945    WY  2024

[750 rows x 3 columns]

In [147]:
# flatten month
wide = unemp_octnov.pivot_table(
    index=["state", "year"],
    columns="month",
    values="unemployment_pct"
).reset_index()
wide = wide.rename(columns={"november":"nov_unemp", "october":"oct_unemp"})

In [148]:
wide

month state  year  nov_unemp  oct_unemp
0        AK  2010        7.9        7.9
1        AK  2011        7.5        7.5
2        AK  2012        7.0        7.0
3        AK  2013        6.9        6.9
4        AK  2014        6.4        6.6
..      ...   ...        ...        ...
700      WY  2020        5.5        5.6
701      WY  2021        3.7        3.9
702      WY  2022        3.4        3.5
703      WY  2023        2.8        2.8
704      WY  2024        3.3        3.3

[705 rows x 4 columns]

In [149]:
# merge on year and state
merged = pd.merge(income_filteryear, wide, on=["state","year"])
merged

     percapita_personalincome state  year  nov_unemp  oct_unemp
0                       33848    AL  2010       10.1       10.1
1                       34884    AL  2011        8.9        9.1
2                       35559    AL  2012        7.8        7.8
3                       35706    AL  2013        7.2        7.2
4                       36722    AL  2014        6.3        6.4
..                        ...   ...   ...        ...        ...
700                     65094    WY  2020        5.5        5.6
701                     70962    WY  2021        3.7        3.9
702                     76394    WY  2022        3.4        3.5
703                     81918    WY  2023        2.8        2.8
704                     85945    WY  2024        3.3        3.3

[705 rows x 5 columns]

In [150]:
# only keep even years for join with elections/midterm years
merged = merged[(merged["year"] == 2010) | (merged["year"] == 2012) | (merged["year"] == 2014) | (merged["year"] == 2018) | (merged["year"] == 2020) | (merged["year"] == 2022) |(merged["year"] == 2024)]
# make year type consistent for merge 
merged.loc[merged['year'] == 2010, 'year'] = 10
merged.loc[merged['year'] == 2012, 'year'] = 12
merged.loc[merged['year'] == 2014, 'year'] = 14
merged.loc[merged['year'] == 2016, 'year'] = 16
merged.loc[merged['year'] == 2018, 'year'] = 18
merged.loc[merged['year'] == 2020, 'year'] = 20
merged.loc[merged['year'] == 2022, 'year'] = 22
merged.loc[merged['year'] == 2024, 'year'] = 24

In [152]:
merged = merged[["state","year","oct_unemp","nov_unemp","percapita_personalincome"]]
merged.head(10)

   state  year  oct_unemp  nov_unemp  percapita_personalincome
0     AL    10       10.1       10.1                     33848
2     AL    12        7.8        7.8                     35559
4     AL    14        6.4        6.3                     36722
8     AL    18        3.8        3.8                     41324
10    AL    20        5.2        4.8                     45843
12    AL    22        2.5        2.4                     51660
14    AL    24        3.1        3.1                     56684
15    AK    10        7.9        7.9                     49543
17    AK    12        7.0        7.0                     53340
19    AK    14        6.6        6.4                     55098

In [158]:
import os
os.getcwd()
os.chdir("/Users/ellawileman/Documents/last_sem/dsci_capstone/final_repo/US-Census-Voting-and-Registration-DSCI-Capstone-Project")

In [159]:
# save to csv that lives in git repo
merged.to_csv('stateecon_indicators.csv', index=False)